package org.sec.Form;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class HowThisWork {
    public JPanel workPanel;
    private JLabel firstLabel;
    private JLabel secondLabel;
    private JLabel thirdLabel;
    private JLabel fourthLabel;
    private JLabel fifthLabel;
    private JLabel sixthLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        workPanel = new JPanel();
        workPanel.setLayout(new GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
        Font workPanelFont = this.$$$getFont$$$("Consolas", -1, 20, workPanel.getFont());
        if (workPanelFont != null) workPanel.setFont(workPanelFont);
        workPanel.setBorder(BorderFactory.createTitledBorder(null, "steps", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        firstLabel = new JLabel();
        Font firstLabelFont = this.$$$getFont$$$("Consolas", -1, 20, firstLabel.getFont());
        if (firstLabelFont != null) firstLabel.setFont(firstLabelFont);
        firstLabel.setText("1. 获取输入的 Jsp 文件或列表,并将其一个个编译为 .java 文件 (通过原生的依赖来编译,而非模版)");
        workPanel.add(firstLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        secondLabel = new JLabel();
        Font secondLabelFont = this.$$$getFont$$$("Consolas", -1, 20, secondLabel.getFont());
        if (secondLabelFont != null) secondLabel.setFont(secondLabelFont);
        secondLabel.setText("2. 使用 ASM 库获取每个 .java 文件中 _jspService 函数所使用的所有函数和类");
        workPanel.add(secondLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        thirdLabel = new JLabel();
        Font thirdLabelFont = this.$$$getFont$$$("Consolas", -1, 20, thirdLabel.getFont());
        if (thirdLabelFont != null) thirdLabel.setFont(thirdLabelFont);
        thirdLabel.setText("3. 在每个方法中查找所有方法调用");
        workPanel.add(thirdLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        fourthLabel = new JLabel();
        Font fourthLabelFont = this.$$$getFont$$$("Consolas", -1, 20, fourthLabel.getFont());
        if (fourthLabelFont != null) fourthLabel.setFont(fourthLabelFont);
        fourthLabel.setText("4. 拓扑排序方法,得知调用顺序");
        workPanel.add(fourthLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        fifthLabel = new JLabel();
        Font fifthLabelFont = this.$$$getFont$$$("Consolas", -1, 20, fifthLabel.getFont());
        if (fifthLabelFont != null) fifthLabel.setFont(fifthLabelFont);
        fifthLabel.setText("5. 在方法调用之间获取参数污点,主要是通过外部源入手,将外部源会用到的函数进行匹配并将其作为 source");
        workPanel.add(fifthLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        sixthLabel = new JLabel();
        Font sixthLabelFont = this.$$$getFont$$$("Consolas", -1, 20, sixthLabel.getFont());
        if (sixthLabelFont != null) sixthLabel.setFont(sixthLabelFont);
        sixthLabel.setText("6. 通过模拟栈帧的方式来模拟函数执行过程,如果定义的 source 流入了恶意函数中,则有理由怀疑其为恶意 JSP Webshell");
        workPanel.add(sixthLabel, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return workPanel;
    }

}
